### ISSUE TITLE
Permission to Reuse the Sublime Text Syntax in an MIT-Licensed Project

### ISSUE THREAD

**Issue by tajmone** [uniconproject/unicon#261]
I wanted to ask permission of re-using the [`config/editor/unicon.sublime-syntax`][unicon st] file from this repository to create a derivative work under MIT License.

My goal is to create a full-fledged Sublime Text 4 package for Unicon, and I'd like to use the above file as my starting point and then gradually extend the original syntax file to leverage the new Sublime Text 4 features, as well as adding more package features.

I couldn't find any info about its original author and license, so the only safe assumption is to consider it being under the GNU GPLv2 license governing this repository.

Unfortunately the GPL license(s) don't play out well in the Sublime ecosystem, were the most common license used for packages and assets is the MIT License. Since for my new package I might need to reuse other third party components, the GPL license might lead to license conflict. So, I'm seeking:

1. Permission to reuse [`config/editor/unicon.sublime-syntax`][unicon st] in an MIT licensed derivate project for an Unicon package for Sublime Text (build >= 4000, aka "Sublime Text 4").
2. Info about the original author(s) so I can duly credit him/her/them in my package/repository.

[unicon st]: https://github.com/uniconproject/unicon/blob/master/config/editor/unicon.sublime-syntax

**Comment by Jafaral** [comment]
@tajmone permission granted. Contributions are welcome

**Comment by tajmone** [comment]
Thanks a lot! 

I'll update you with a link when the package is available (also a commit to the txt file with the links to editors packages).

**Comment by tajmone** [comment]
Some updates on the Unicon package...

I've managed to come up with a first release of the Sublime Unicon package for Sublime Text 4:

https://github.com/tajmone/Sublime-Unicon

The package fixes various problems with the original syntax and applies some minor improvements too (which I've also submitted back here via PR #269).

Beside that, I've enabled the new ST4 syntax engine and added `#` comments settings. Not much, but a good start.

I've now submitted the repository to Package Control via pull request:

wbond/package_control_channel#8446

once the new package has been reviewed and approved (it's going to take a few weeks), end users will be able to install it via Sublime Text's native package manager. When this happens, I'll edit the [`config/editor/README`][README] file in this repository to mention the new package and provide a link to its entry at Package Control, and submit a PR.

Hopefully, the new package will grow in the course of time.

[README]: https://github.com/uniconproject/unicon/blob/master/config/editor/README

**Comment by Jafaral** [comment]
Excellent work @tajmone . Thank you for the improvements and also for going the extra mile to upstream the package to Sublime.

**Comment by tajmone** [comment]
# Sublime Unicon Published

The Sublime Unicon package has been approved and it's now available on Package Control:

https://packagecontrol.io/packages/Unicon

Sublime Text 4 users can now install it via the native package manager, which will keep it up to date automatically.

I've created PR #273 to add the new package to the list of supported editors in `config/editor/REAMDE`.
