### ISSUE TITLE
MSYS2 support

### ISSUE THREAD

**Issue by 1e9t8m29** [uniconproject/unicon#292]
For unknown reason, my account @juanchiahsing being flagged by github and hidden from the public. I can't see your replies. I created a new ticket to continue our discussion @Jafaral

**Comment by Jafaral** [comment]
Well, it was there and public all yesterday.  What happened?

**Comment by 1e9t8m29** [comment]
> Well, it was there and public all yesterday. What happened?

I have no idea about it. Today I try logging in and it said my account was flagged. I logout and visit the projects I usually contributed to and realized everything related to me (my tickets, my discussions, my comments, my public projects, my pull requests,...) all disappeared. It's like I have never existed. This is the first time I tasted the West's cancel culture that I hear many people around me talking about but I personally have no idea about.

**Comment by Jafaral** [comment]
`./configure --enable-debug --enable-verbosebuild` , rebuild urtt under `src/rtt`. urrt was crashing in your build which means something fundamentally wrong about the build and/or the environment.

**Comment by 1e9t8m29** [comment]
> `./configure --enable-debug --enable-verbosebuild` , rebuild urtt under `src/rtt`. urrt was crashing in your build which means something fundamentally wrong about the build and/or the environment.

No additional information. It's simply said it's segmentation faulted.

**Comment by Jafaral** [comment]
run `urtt` under gdb and se what it is crashing.

**Comment by 1e9t8m29** [comment]
> run `urtt` under gdb and se what it is crashing.

Out of my ability. JavaScript developer doesn't know how to use gdb :smile:

**Comment by 1e9t8m29** [comment]
But, if it's failing for MSYS2 very likely it's also failing for original MSYS. If it's not, the culprit very likely be the GCC 12.2 compiler used by MSYS2. Your code maybe incompatible with this modern GCC. TDM GCC is not updated since a long time. If you want a non-MSYS2 standalone GCC, please download from here instead of TDM: https://winlibs.com/

Please re-check if it's really building on Windows or not.

**Comment by Jafaral** [comment]
There are too many variables on Windows and it is hard to control all of them, at least without a significant effort. I'm sure it can be made to work but someone has to volunteer to do the work. That fact that it fails on MSYS2 has nothing to do with MSYS. Even with the older version of GCC things worked with MSYS and not MSYS2. I use newer GCC version Linux so it is not just about GCC alone. MSYS and MSYS2 are both attempts to make Windows look like Linux and they both have their own assumptions.

**Comment by Don-Ward** [comment]
> But, if it's failing for MSYS2 very likely it's also failing for original MSYS. If it's not, the culprit very likely be the GCC 12.2 compiler used by MSYS2. Your code maybe incompatible with this modern GCC. TDM GCC is not updated for a long time. If you want a non-MSYS2 standalone GCC, please download from here instead of TDM: https://winlibs.com/
> 
> Please re-check if it's really building on Windows or not.

I have used the UCRT64 environment of MSYS2 to build Unicon succesfully. In the initial stages of the work, rtt crashed for me too. I'm willing to bet your crash is because of a problem with wildcard expansion  using FINDFIRST and FINDNEXT. My code is not yet ready for prime time, but expect a series of commits that enable Unicon to be built using MSYS2/UCRT64  (and gcc 12.2) in the near future.  
I agree with Jafar (MSYS != MSYS2). One significant difference is that MSYS is 32bit whereas MSYS2 is largely 64bit. The bug in FINDFIRST/FINDNEXT is only triggered on a 64bit system.
