### ISSUE TITLE
Editors and IDEs support?

### ISSUE THREAD

**Issue by 1e9t8m29** [uniconproject/unicon#293]
It seems there is none at the moment. I suggest adding at least syntax highlighting to CudaText: https://github.com/Alexey-T/CudaText

CudaText is inspired by SublimeText but is more lightweight and available for more platforms.

**Comment by Jafaral** [comment]
see : https://github.com/uniconproject/unicon/tree/master/config/editor

There is support for sublime, you are welcome to adapt that if it works with CudaText.
