### ISSUE TITLE
13.2 - IDE paths pointing to wrong locations

### ISSUE THREAD

**Issue by lpvm** [uniconproject/unicon#407]
Hi,

I'm learning Unicon and installed version 13.2.  
Couldn't compile the newest commit.

The configuration was done as
`./configure --prefix=/usr/local`

At the IDE (ui), when I try to access some help, the IDE expects to find the documents at  `/usr/local/bindoc/utr/`.

But the config script have installed them at `/usr/local/share/doc/unicon`.

Maybe this is already fixed for current version.

But is there a way to change these paths for 13.2?

Couldn't find that option available in the UI.

Thanks.

**Comment by Jafaral** [comment]
This needs to be fixed. Thanks for the report @lpvm.

By the way, we have been working on adding Unicon support to VSCode. See http://unicon.org/ for info about Unicon extensions.

**Comment by lpvm** [comment]
Thank you.
I use `vim` normally, but could use the `ui` for learning the language.
