### ISSUE TITLE
make now fails when trying to build a main unicon program

### ISSUE THREAD

**Issue by StephenWampler** [uniconproject/unicon#456]
With the current github repository attempting to make (with or without -j8) I get a failure when unicon is called to build a main program:

```
make[3]: Leaving directory '/opt/unicon/uni/udb/dta'
../../bin/unicon -s -c  state

Run-time error 117 in startup code
missing main procedure
make[2]: *** [Makefile:78: state.u] Error 1
make[2]: Leaving directory '/opt/unicon/uni/udb'
make[1]: *** [Makefile:22: nographics] Error 2
make[1]: Leaving directory '/opt/unicon/uni'
make: *** [Makefile:23: default_target] Error 2
```
Also, attempting to rebuild any Unicon program gives the same error:

```
->unicon qmazer.icn

Run-time error 117 in startup code
missing main procedure
->
```

**Comment by StephenWampler** [comment]
Oh, this is on Ubuntu 22.04.

**Comment by StephenWampler** [comment]
Go figure.  It's working now.  I swear I didn't do anything except eat dinner!

**Comment by Jafaral** [comment]
There were earlier reports that dinner does cause issues sometimes,  so that is a possible explanation  😄
